### ISSUE TITLE
File "/opt/zabbix/cloudwatch/zabbixCloudWatch.py", line 370, in <module>

### ISSUE THREAD

**Issue by nicolasfortier75** [omni-lchen/zabbix-cloudwatch#22]
Hi,  I got this error msg... 

Traceback (most recent call last):
  File "/opt/zabbix/cloudwatch/zabbixCloudWatch.py", line 370, in <module>
    cw_data = getCloudWatchData(aws_account, aws_region, aws_service, dimensions)
  File "/opt/zabbix/cloudwatch/zabbixCloudWatch.py", line 172, in getCloudWatchData
    aws_metrics = json.loads(open(aws_services_conf).read())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 10 - line 403 column 1 (char 9 - 9190)

**Comment by magnetogit** [comment]
solved , invalid path

**Comment by nicolasfortier75** [comment]
For any cron script.

**Comment by nicolasfortier75** [comment]
invalid Path?

**Comment by nicolasfortier75** [comment]
Can you specify what's wrong with path?

In my script:
PATH=$PATH:/opt/zabbix/cloudwatch
export PATH

/opt/zabbix/cloudwatch$ ls
awsAccount.py  awsConnection.py  awsLLD.py  awsLLD.sh  conf  cron.CloudFront.sh  cron.d  cron.RDS.sh  pyZabbixSender.py  README.md  templates  zabbixCloudWatch.py

**Comment by magnetogit** [comment]
I used /opt/zabbix/cloudwatch/zabbix-cloudwatch/cron.d/cron.RDS.sh ,That error ,Because script fix path as PATH=$PATH:/opt/zabbix/cloudwatch

**Comment by nicolasfortier75** [comment]
If my PATH was not good... I would get... 

zabbixCloudWatch.py: command not found
