### ISSUE TITLE
 File "/opt/zabbix/cloudwatch/zabbixCloudWatch.py", line 370, in <module>     cw_data = getCloudWatchData(aws_account, aws_region, aws_service, dimensions)

### ISSUE THREAD

**Issue by chrisbeagleai** [omni-lchen/zabbix-cloudwatch#28]
I was really happy to see someone created this integration. Its well done. Having one issue collecting data. 

Traceback (most recent call last):
  File "/opt/zabbix/cloudwatch/zabbixCloudWatch.py", line 370, in <module>
    cw_data = getCloudWatchData(aws_account, aws_region, aws_service, dimensions)
  File "/opt/zabbix/cloudwatch/zabbixCloudWatch.py", line 154, in getCloudWatchData
    aws_account = awsAccount(account)
  File "/opt/zabbix/cloudwatch/awsAccount.py", line 20, in __init__
    options = Config.options(account)
  File "/usr/lib/python2.7/ConfigParser.py", line 279, in options
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: ''

**Comment by plutocrat** [comment]
Is the account name (between the square brackets in awscred), the same as the one after ACCOUNT= in your cron script?
