### ISSUE TITLE
error in running  zabbixCloudWatch.py  script

### ISSUE THREAD

**Issue by RahPraSingh** [omni-lchen/zabbix-cloudwatch#52]
Hi while running below command , i am getting below error 

/usr/bin/python /opt/zabbix/cloudwatch/zabbixCloudWatch.py -z "172.31.31.18" -x "aniltariyal4c.mylabserver.com" -a "rahprasingh" -r "ap-south-1a" -s "RDS" -d "zabbixdb" -p "300" -f "2019-09-18 16:20:00" -t "2019-09-18 16:25:00"

Traceback (most recent call last):
  File "/opt/zabbix/cloudwatch/zabbixCloudWatch.py", line 352, in <module>
    dimensions = dimConvert(options.dimensions)
  File "/opt/zabbix/cloudwatch/zabbixCloudWatch.py", line 50, in dimConvert
    dim[secondSplit[0]] = secondSplit[1]
IndexError: list index out of range

i have only basic knowledge of python , pls help

**Comment by omni-lchen** [comment]
The format of dimension is not in a correct format, where the -d argument is,  please check the bash scripts in cron.d folder for some examples.
