### ISSUE TITLE
Pulling metrics for RDS

### ISSUE THREAD

**Issue by isaiah213** [omni-lchen/zabbix-cloudwatch#8]
I am currently running Zabbix 3.2 and running into the below issue when pulling the metrics for RDS.  However, metrics for ELB work without a issue.  Not sure if this is due to the last update that fixed the date timestamp.  Looks like its not returning any metrics in the array as well.  Can you please help with this?  Thanks!

```
Traceback (most recent call last):
  File "/opt/zabbix/cloudwatch/zabbixCloudWatch.py", line 368, in <module>
    sendLatestCloudWatchData(zabbix_server, zabbix_host, cw_data)
  File "/opt/zabbix/cloudwatch/zabbixCloudWatch.py", line 221, in sendLatestCloudWatchData
    zabbix_key_timestamp = int(time.mktime(sorts[0]['Timestamp'].timetuple()))
UnboundLocalError: local variable 'sorts' referenced before assignment
```

**Comment by isaiah213** [comment]
Fixed it using the below merge request that fixed the problem.  Thanks!

https://github.com/omni-lchen/zabbix-cloudwatch/pull/7
